# NumPy 操作
ndarray类的实例可以通过本教程后面描述的不同的数组创建例程来构造。 基本的ndarray是使用 NumPy 中的数组函数创建的，如下所示：

In [ ]:
numpy.array

### 它从任何暴露数组接口的对象，或从返回数组的任何方法创建一个ndarray。

In [ ]:
 numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

上面的构造器接受以下参数：
![1](./插图/1.png)

In [1]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [2]:
# 多于一个维度
import numpy as np
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [3]:
# 最小维度
import numpy as np
a = np.array([1,2,3,4,5], ndmin = 2)
a

array([[1, 2, 3, 4, 5]])

In [4]:
# dtype 参数
import numpy as np
a = np.array([1,2,3], dtype = complex)
a

array([1.+0.j, 2.+0.j, 3.+0.j])

# NumPy - 数据类型
NumPy 支持比 Python 更多种类的数值类型。 下表显示了 NumPy 中定义的不同标量数据类型。

![2](./插图/2.png)
NumPy 数字类型是dtype（数据类型）对象的实例，每个对象具有唯一的特征。 这些类型可以是np.bool_，np.float32等。

# 数据类型对象 (dtype)
数据类型对象描述了对应于数组的固定内存块的解释，取决于以下方面：

+ 数据类型（整数、浮点或者 Python 对象）

+ 数据大小

+ 字节序（小端或大端）

在结构化类型的情况下，字段的名称，每个字段的数据类型，和每个字段占用的内存块部分。

如果数据类型是子序列，它的形状和数据类型。

字节顺序取决于数据类型的前缀<或>。 <意味着编码是小端（最小有效字节存储在最小地址中）。 >意味着编码是大端（最大有效字节存储在最小地址中）。

dtype可由一下语法构造：

In [ ]:
numpy.dtype(object, align, copy)

参数为：

+ Object：被转换为数据类型的对象。

+ Align：如果为true，则向字段添加间隔，使其类似 C 的结构体。

+ Copy：生成dtype对象的新副本，如果为flase，结果是内建数据类型对象的引用。

In [9]:
# 使用数组标量类型
import numpy as np
dt = np.dtype(np.int32)
dt

dtype('int32')

In [10]:
# int8,int16,int32,int64 可替换为等价的字符串 'i1','i2','i4',以及其他。
import numpy as np
dt = np.dtype('i4')
dt

dtype('int32')

In [11]:
# 使用端记号
import numpy as np
dt = np.dtype('>i4')
dt

dtype('>i4')

下面的例子展示了结构化数据类型的使用。 这里声明了字段名称和相应的标量数据类型。

In [12]:
# 首先创建结构化数据类型
import numpy as np
dt = np.dtype([('age', np.int8)])
dt

dtype([('age', 'i1')])

In [14]:
# 现在将其应用于 ndarray 对象
import numpy as np

dt = np.dtype([('age', np.int8)])
a = np.array([(10,),(20,),(30,)], dtype = dt)
a

array([(10,), (20,), (30,)], dtype=[('age', 'i1')])

In [15]:
# 文件名称可用于访问 age 列的内容
import numpy as np

dt = np.dtype([('age', np.int8)])
a = np.array([(10,),(20,),(30,)], dtype = dt)
a['age']

array([10, 20, 30], dtype=int8)

以下示例定义名为 student 的结构化数据类型，
其中包含字符串字段name，整数字段age和浮点字段marks。 此dtype应用于ndarray对象。

In [21]:
import numpy as np
student = np.dtype([('name','S20'),('age','i1'),('marks','f4')])
student

dtype([('name', 'S20'), ('age', 'i1'), ('marks', '<f4')])

In [26]:
import numpy as np
student = np.dtype([('name','S20'),('age','i1'),('marks','f4')])
a = np.array([('abc',21,50),('xyz',18,75)],dtype = student)
a

array([(b'abc', 21, 50.), (b'xyz', 18, 75.)],
      dtype=[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')])

In [ ]:
# 实际输出结果应该如下：
[('abc', 21, 50.0), ('xyz', 18, 75.0)]

### 每个内建类型都有一个唯一定义它的字符代码：

+ 'b'：布尔值

+ 'i'：符号整数

+ 'u'：无符号整数

+ 'f'：浮点

+ 'c'：复数浮点

+ 'm'：时间间隔

+ 'M'：日期时间

+ 'O'：Python 对象

+ 'S', 'a'：字节串

+ 'U'：Unicode

+ 'V'：原始数据（void）